---
- name: IPV6 Deployment
  hosts: test-device
  gather_facts: false
  connection: network-cli

  tasks:
    - name: Enabling IPv6 Unicast Routing
      ios_config:
        lines:
          - ipv6 unicast-routing
          - ipv6 cef distributed

    - name: Enable OSPFv3
      ios_config:
        lines:
          - address-family ipv6 unicast
        parents:
          - router ospfv3 1

# For Older Switches Interface ID's will be different 
# Please Change the Interface ID's accordingly
#
    - name: Configuring IPv6 on Interface Connecting to MPLS Router
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:12::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
          - ospfv3 1 ipv6 network point-to-point
        parents: interface GigabitEthernet1/0/1
        match: exact

    - name: Configuring IPv6 on Interface Connecting to VPN Router
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:11::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
          - ospfv3 1 ipv6 network point-to-point
        parents: interface GigabitEthernet1/0/48
        match: exact

    - name: Configuring IPv6 on Loopback
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:1::1/128
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface loopback0
        match: exact

# VLAN ID's may be different in some sites so make sure 
# You have the right VLAN ID's assigned for the respective sites 
#

    - name: Configuring IPv6 for VLAN37 (Employee Wireless)
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:2::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface VLAN37
        match: exact

    - name: Configuring IPv6 for VLAN35 (Internet Wireless)
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:3::1/64
          - ipv6 enable
          - ipv6 nd ra interval 30
          - ipv6 nd ra dns server 2620:119:35::35
          - ipv6 nd ra dns server 2620:119:35::53
          - ospfv3 1 ipv6 area 0
        parents: interface VLAN35
        match: exact

    - name: Configuring IPv6 for VLAN40 (Server VLAN)
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:7::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface VLAN40
        match: exact

    - name: Configuring IPv6 for VLAN8 (Data VLAN)
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:8::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface VLAN8
        match: exact

#    - name: Configuring IPv6 for VLAN12 (SIG ANET)
#      ios_config:
#        lines:
#          - ipv6 address 2620:12D:E022:c::1/64
#          - ipv6 enable
#          - ospfv3 1 ipv6 area 0
#        parents: interface Vlan12
#        match: exact

    - name: Configuring IPv6 for VLAN13 (Voice VLAN)
      ios_config:
        lines:
          - description Voice-Vlan
          - ipv6 address 2620:12D:E022:9::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface Vlan13
        match: exact

#    - name: Configuring IPv6 for VLAN888
#      ios_config:
#        lines:
#          - ipv6 address 2620:12D:E022::1/64
#          - ipv6 enable
#          - ospfv3 1 ipv6 area 0
#        parents: interface Vlan100
#        match: exact

    - name: Configuring IPv6 for VLAN3000
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:D::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface Vlan3000
        match: exact

    - name: Configuring IPv6 for VLAN3001
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:E::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface Vlan3001
        match: exact

    - name: Configuring IPv6 for VLAN3002
      ios_config:
        lines:
          - ipv6 address 2620:12D:E022:F::1/64
          - ipv6 enable
          - ospfv3 1 ipv6 area 0
        parents: interface Vlan3002
        match: exact

    - name: Access-list SNPS-ACCESS-ONLY-V6
      ios_config:
        lines:
          - permit ipv6 2400:B3C0::/32 any
          - permit ipv6 2620:12D:E000::/40 any
          - permit ipv6 2A0C:D400::/29 any
        parents: ipv6 access-list SNPS-ACCESS-ONLY-V6
        match: exact

    - name: Adding TACACS to line vty 0 4
      ios_config:
        lines:
          - ipv6 access-class SNPS-ACCESS-ONLY-V6 in
        parents: line vty 0 4
        match: exact

##----------------- For DC Network Only ---------------------------#

#Please Enable the below steps for DC network 

# Make sure to enable IPV6 Address family for the DC and LAB VRF's
#
#    - name: Enabling IPv6 Address family for DC VRF
#      ios_config:
#        lines:
#          - address-family ipv6
#        parents:
#          - vrf definition DC
#          - rd 100:100
#        match: exact
#
#    - name: Enabling IPv6 Address family for LAB VRF
#      ios_config:
#        lines:
#          - address-family ipv6
#        parents:
#          - vrf definition LAB
#          - rd 200:200
#        match: exact
#
#    - name: Enable OSPFv3 1 for Default VRF 
#      ios_config:
#        lines:
#          - area 7.0.0.0 nssa no-summary
#        parents:
#          - router ospfv3 1
#          - address-family ipv6 unicast
#
#    - name: Enable OSPFv3 7 for DC VRF
#      ios_config:
#        lines:
#          - capability vrf-lite
#          - area 7.0.0.0 nssa no-summary
#        parents:
#          - router ospfv3 7 
#          - address-family ipv6 unicast vrf DC
#
#    - name: Enable OSPFv3 8 for LAB VRF
#      ios_config:
#        lines:
#          - capability vrf-lite
#          - area 7.0.0.0 nssa no-summary
#        parents:
#          - router ospfv3 8 
#          - address-family ipv6 unicast vrf LAB
#
#    - name: Save the Configuration
#      ios_config:
#        save_when: modified