---
- name: TACACS AND RADIUS CONFIG FORMAT UPDATE
  hosts: test-device
  gather_facts: false
  connection: network-cli

  tasks:
    - name: Verify logging server
      ios_command:
        commands:
          - show run | in logging host
      register: output
    - name: Print Output
      debug: var=output

    - name: Remove old logging server
      ios_config:
        lines:
          - "{{'no ' + item}}"
      ignore_errors: yes
      loop: "{{output.stdout_lines[0]}}"
      when:
        - output.stdout_lines[0] != ["logging host 10.200.17.66"]
        - output.stdout_lines[0] != [""]

    - name: Adding Service Timestamps for Debug and Logs
      ios_config:
        lines:
          - service timestamps debug datetime localtime show-timezone
          - service timestamps log datetime localtime show-timezone

    - name: Adding new logging server
      ios_config:
        lines:
          - logging host 10.200.17.66
          - logging buffered 100000
          - logging facility local0
          - logging trap debugging
          - logging source-interface Loopback0                                           ## < ---------- VLAN CHANGE ###

    - name: Removing TACACS Source configuration from Global Config
      ios_config:
        lines:
          - no ip tacacs source-interface Loopback0                                      ## < ---------- VLAN CHANGE ###

    - name: Removing older TACACS entries
      ios_config:
        lines: 
          - no tacacs-server host 10.225.16.1
          - no tacacs-server host 10.13.191.246
          - no tacacs-server host 10.15.72.1
          - no tacacs-server host 10.130.65.79
          - no tacacs-server host 10.200.17.69
          - no tacacs-server host 10.15.152.160
          - no tacacs-server host 10.4.124.220
        match: exact
      ignore_errors: yes

    - name: Removing IP entries from AAA Profile 
      ios_config:
        lines:
          - no server 10.15.72.1
          - no server 10.13.191.246
          - no server 10.130.65.79
          - no server 10.200.17.69
          - no server 10.15.152.160
          - no server 10.4.124.220
          - no server 10.225.16.1
          - no server 
        parents: aaa group server tacacs+ Acs-Box
        match: exact
      ignore_errors: yes

##### Changing the TACACS template with new format #####
#

    - name: Changing TACACS format for cn58cppm01
      ios_config:
        lines:
          - address ipv4 10.132.50.4
          - key cppmcisco
        parents: tacacs server cn58cppm01

#    - name: Changing TACACS format for us01cppm01
#      ios_config:
#        lines:
#          - address ipv4 10.200.17.69
#          - key cppmcisco
#        parents: tacacs server us01cppm01

    - name: Changing TACACS format for jp01cppm01
      ios_config:
        lines:
          - address ipv4 10.128.36.236
          - key cppmcisco
        parents: tacacs server jp01cppm01

#    - name: Changing TACACS format for us01cppm02
#      ios_config:
#        lines:
#          - address ipv4 10.15.72.1
#          - key cppmcisco
#        parents: tacacs server us01cppm02  

#    - name: Changing TACACS format for mdccppm01
#      ios_config:
#        lines:
#          - address ipv4 10.225.16.1
#          - key cppmcisco
#        parents: tacacs server mdccppm01

    - name: Changing TACACS format for indccppm01
      ios_config:
        lines:
          - address ipv4 10.144.172.54
          - key cppmcisco
        parents: tacacs server indccppm01


#    - name: Changing TACACS format for cn58cppm01
#      ios_config:
#        lines:
#          - address ipv4 10.132.50.4
#          - key cppmcisco
#        parents: tacacs server cn58cppm01


#### Make sure the Source interface is the right VLAN #####


    - name: Changing AAA group to include the new format 
      ios_config:
        lines:
#          - server name us01cppm01
#         - server name us01cppm02
#          - server name mdccppm01
#          - server name cn58cppm01
          - server name jp01cppm01
          - server name cn58cppm01
          - server name indccppm01
          - ip tacacs source-interface Loopback0                                        ## < ---------- VLAN CHANGE ###
        parents: aaa group server tacacs+ Acs-Box  


#### Adding Radius Servers and Editing Old US01CPPM01 IP address ####

    - name: Adding cn58cppm01 Server List
      ios_config:
        lines:
          - address ipv4 10.132.50.4 auth-port 1812 acct-port 1813
          - automate-tester username dummy probe-on
          - key cppmcisco
        parents: radius server cn58cppm01
        match: exact

    - name: Adding jp01cppm01 Server List
      ios_config:
        lines:
          - address ipv4 10.128.36.236 auth-port 1812 acct-port 1813
          - automate-tester username dummy probe-on
          - key cppmcisco
        parents: radius server jp01cppm01
        match: exact

#    - name: Adding cn42cppm01 Server List
#      ios_config:
#        lines:
#          - address ipv4 10.130.65.79 auth-port 1812 acct-port 1813
#          - automate-tester username dummy probe-on
#          - key cppmcisco
#        parents: radius server cn42cppm01
#        match: exact

#    - name: Adding mdccppm01 Server List
#      ios_config:
#        lines:
#          - address ipv4 10.225.16.1 auth-port 1812 acct-port 1813
#          - automate-tester username dummy probe-on
#          - key cppmcisco
#        parents: radius server mdccppm01
#        match: exact

#    - name: Adding us01cppm02 Server List
#      ios_config:
#        lines:
#          - address ipv4 10.15.72.1 auth-port 1812 acct-port 1813
#          - automate-tester username dummy probe-on
#          - key cppmcisco
#        parents: radius server us01cppm02
#        match: exact

#    - name: Adding us01cppm01 Server List
#      ios_config:
#        lines:
#          - address ipv4 10.200.17.69 auth-port 1812 acct-port 1813
#          - automate-tester username dummy probe-on
#          - key cppmcisco
#        parents: radius server us01cppm01
#        match: exact

    - name: Adding Radius Server List
      ios_config:
        lines:
          - client 10.128.36.236 server-key cppmcisco
          - client 10.132.50.4 server-key cppmcisco
#          - client 10.225.16.1 server-key cppmcisco
#          - client 10.200.17.69 server-key cppmcisco
#          - client 10.130.65.79 server-key cppmcisco
#          - client 10.15.72.1 server-key cppmcisco
          - port 3799
          - auth-type all
        parents: aaa server radius dynamic-author
        match: exact

    - name: Adding CN58 and JP01 CPPM Servers to the Group List
      ios_config:
        lines:
          - server name jp01cppm01
          - server name cn58cppm01
#          - server name cn42cppm01
#          - server name mdccppm01
#          - server name us01cppm02
#          - server name us01cppm01
          - ip radius source-interface Loopback0                     ## < ---------- VLAN CHANGE ###
        parents: aaa group server radius clearpass
        match : exact

    - name: Remove Old Radius Config Format 
      ios_config:
        lines:
          - no server-private 10.15.72.1 
          - no server 10.15.72.1 auth-port 1812 acct-port 1813
          - no server-private 10.13.191.246 
          - no server 10.13.191.246 auth-port 1812 acct-port 1813
          - no server-private 10.130.65.79 
          - no server 10.130.65.79 auth-port 1812 acct-port 1813
          - no server-private 10.200.17.69 
          - no server 10.200.17.69 auth-port 1812 acct-port 1813
        parents: aaa group server radius clearpass
        match : exact
      ignore_errors: yes

    - name: Remove old us01cppm01 IP for Radius Template
      ios_config:
        lines:
          - no client 10.13.191.246
        parents: aaa server radius dynamic-author
        match : exact
      ignore_errors: yes

    - name: Remove OLD and Unwanted Radius Servers from Radius Config
      ios_config:
        lines:
          - no client 10.130.65.79
          - no client 10.225.16.1
#          - no client 10.128.36.236
          - no client 10.200.17.69
        parents: aaa server radius dynamic-author
        match : exact
      ignore_errors: yes

    - name: Remove CPPM Server Radius Config 
      ios_config:
        lines:
          - no server name cn42cppm01
          - no server name mdccppm01
          - no server name us01cppm01
        parents: aaa group server radius clearpass
        match : exact
      ignore_errors: yes

    - name: Remove CPPM Radius Server Radius Config 
      ios_config:
        lines:
          - no radius server cn42cppm01
          - no radius server us01cppm01                            
      ignore_errors: yes

    - name: Remove CPPM Server Source Interface from Global Config
      ios_config:
        lines:
          - no ip radius source-interface Loopback0                                  #   < ------ Change the Source Interface Accordingly
      ignore_errors: yes
    

## Adding Config Archive Logging ###

    - name: Adding Config Archive logging
      ios_config:
        lines:
          - logging enable
          - logging size 200
          - notify syslog contenttype plaintext
          - hidekeys
        parents:
          - archive
          - log config

## Adding Security Hardening Template 

    - name: Disable smart install
      ios_config:
        lines:
          - no vstack
      ignore_errors: yes

    - name: Disable SSHv1
      ios_config:
        lines:
          - no ip ssh version
          - ip ssh version 2
      ignore_errors: yes

    - name: Disable http/https
      ios_config:
        lines:
          - no ip http server
          - no ip http secure-server
      ignore_errors: yes

    - name: Disable Telnet
      ios_config:
        lines:
          - transport input ssh
        parents: line vty 0 4

    - name: Resolve NTP Information Disclosure Vulnerability
      ios_config:
        lines:
          - permit 10.228.0.1
          - permit 10.228.0.2
          - permit 10.228.0.3
          - permit 10.228.0.4
          - permit 10.228.0.5
        parents: ip access-list standard NTP_ACCESS
        before: no ip access-list standard NTP_ACCESS
        match: exact

    - name: Resolve NTP Information Disclosure Vulnerability
      ios_config:
        lines:
          - ntp access-group peer NTP_ACCESS

    - name: Enable Service Password Encryption
      ios_config:
        lines:
          - service password-encryption
      ignore_errors: yes

    - name: Save the running-config if modified
      ios_config:
        save_when: modified

    - name: Save the Configuration
      ios_config:
        save_when: modified
